# Generated by Django 5.0.3 on 2024-04-02 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alura', '0007_alter_pedido_table_alter_pedidodetalle_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='alura.cliente')),
                ('detalle_pedido', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='alura.pedidodetalle')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='alura.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='alura.curso')),
            ],
            options={
                'db_table': 'tbl_mis_compras',
            },
        ),
    ]
