# Generated by Django 5.0.3 on 2024-04-02 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alura', '0008_miscompras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miscompras',
            name='detalle_pedido',
        ),
    ]
