# Generated by Django 5.0.3 on 2024-04-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alura', '0009_remove_miscompras_detalle_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='inclu_a',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='inclu_b',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='inclu_c',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='inclu_d',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='inclu_e',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='inclu_f',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='nota_d',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='nota_e',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='nota_f',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='nota_g',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='nota_h',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='nota_i',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='nota_j',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_a_detalle_a',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_a_detalle_b',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_a_detalle_c',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_b_detalle_a',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_b_detalle_b',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_b_detalle_c',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_b_detalle_d',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_b_detalle_e',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_c_detalle_a',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_c_detalle_b',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_c_detalle_c',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_conten_titulo_a',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_conten_titulo_b',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_conten_titulo_c',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_conten_titulo_d',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_conten_titulo_e',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_conten_titulo_f',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_conten_titulo_g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_conten_titulo_h',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_conten_titulo_i',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_conten_titulo_j',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_d_detalle_a',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_d_detalle_b',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_e_detalle_a',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_e_detalle_b',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_e_detalle_c',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_f_detalle_a',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_f_detalle_b',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_g_detalle_a',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_g_detalle_b',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_g_detalle_c',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_h_detalle_a',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_h_detalle_b',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_h_detalle_c',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_h_detalle_d',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_i_detalle_a',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_i_detalle_b',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_i_detalle_c',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_i_detalle_d',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_j_detalle_a',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='MisCompras',
        ),
    ]
