# Generated by Django 5.0.3 on 2024-04-10 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alura', '0011_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='contenido',
            new_name='content',
        ),
    ]
